divert(-1)
define(`，', `, ')
define(`；', `; ')
define(`：', `: ')
define(`“', `"')
define(`”', `"')
define(`（', ` (')
define(`）', `)')
define(`·', `.')
define(`偏', ` 偏 ')
define(`位于', ` 位于 ')
define(`标注', ` 标注 ')
define(`章', `\chapter{$1}')
divert(0)dnl
